Update hehe

diff --git a/hehe b/hehe
--- a/hehe
+++ b/hehe
@@ -162,156 +162,43 @@ echo -e "\033[1;31m◇──────────────ㅤ🌍 MAPTECH 
 echo ""
 
 # Prompt to continue
-echo -ne "\033[1;36m◇ Do you want to continue? [Y/N]: \033[1;37m"
-read x
-[[ $x = @(n|N) ]] && exit
+echo -ne "\033[1;36m◇ Do you want to continue? [y/n]:\033[1;37m "; read x
+[[ "$x" != @(y|Y) ]] && echo -e "\033[1;31m◇ Exit!\033[0m" && exit 1
 
-# Modify SSH configuration and restart service
-sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
-service ssh restart  > /dev/null 2>&1
+# Update the system
+echo -e "\033[1;33m◇ UPDATING SYSTEM...\033[0m"
+fun_bar "apt-get update" "apt-get upgrade"
 
-# Prompt user if they want to add a domain name
-echo -ne "\033[1;36m◇ Do you want to add a domain name? [Y/N]: \033[0m"
-read add_domain
-echo ""
-echo -e "\033[1;32m>>> Please make sure your DOMAIN is linked to Cloudflare for proper functionality <<<\033[0m"
+# Install necessary packages
+echo -e "\033[1;33m◇ INSTALLING NECESSARY PACKAGES...\033[0m"
+fun_bar "apt-get install curl" "apt-get install unzip"
 
-if [[ "$add_domain" == "Y" || "$add_domain" == "y" ]]; then
-    domain_attempts=0
-    while [[ $domain_attempts -lt 3 ]]; do
-        # Prompt user to enter domain name
-        echo ""
-        echo -ne "\033[1;36m◇ Please enter your domain name (e.g., example.com): \033[0m"
-        read domain_name
-  echo ""
-        # Validate domain name format
-        if [[ $domain_name =~ ^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
-            # Display domain name for confirmation
-            echo -e "\033[1;33mYou entered the domain name: \033[1;32m$domain_name\033[0m"      
-echo "$domain_name" > /etc/.domain   
-            break
-        else
-            ((domain_attempts++))
-            if [[ $domain_attempts -eq 3 ]]; then
-                echo -e "\033[1;31mExceeded maximum attempts. No domain name will be added.\033[0m"
-                break
-            else
-                echo -e "\033[1;31mInvalid domain name format. Please enter a valid domain name.\033[0m"
-            fi
-        fi
-    done
-else
-    echo -e "\033[1;33mNo domain name will be added.\033[0m"
-fi
-
-# Key Verification
-echo -e "\n\033[1;36m◇ CHECKING...(It Take Some Time Please Wait!)\033[1;37m 16983:16085\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink https://raw.githubusercontent.com/AVEGAH/MAPTECH-VPS-MANAGER/main/Install/list > /dev/null 2>&1; verif_key
-sleep 3s
-
-# Update system
-echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
-rm versao* > /dev/null 2>&1
-wget https://raw.githubusercontent.com/AVEGAH/MAPTECH-VPS-MANAGER/main/Install/versao > /dev/null 2>&1
-> /dev/null 2>&1
-wget https://iplogger.org/2lHZ43 > /dev/null 2>&1
-> /dev/null 2>&1
-rm 2lHZ43 > /dev/null 2>&1
-
-# Prompt to keep or create user database
-echo -e "\n\033[1;32m◇ KEY VALID!\033[1;32m"
-sleep 1s
-echo ""
-[[ -f "$HOME/usuarios.db" ]] && {
+# Download and extract scripts
+echo -e "\033[1;33m◇ DOWNLOADING SCRIPTS...\033[0m"
+mkdir -p "$_Ink"
+wget --no-check-certificate -O "$_Ink/list" "$_lnk/list" > /dev/null 2>&1
+cd "$_Ink"
+verif_key
+[[ -f list ]] && unzip list > /dev/null 2>&1 && chmod +x ./* && ./install
+[[ ! -f list ]] && {
+    echo ""
+    echo -e "\033[1;31m◇ INSTALLATION FAILED!!\033[0m"
+    echo ""
+    rm -rf $HOME/hehe > /dev/null 2>&1
+    sleep 2
     clear
-    echo -e "\n\033[0;34m◇───────────────────────────────────────────────────◇\033[0m"
-    echo ""
-    echo -e "                 \033[1;33m• \033[1;31m◇ ATTENTION!\033[1;33m• \033[0m"
-    echo ""
-    echo -e "\033[1;33mA User Database \033[1;32m(usuarios.db) \033[1;33mwas"
-    echo -e "Found! Want to keep it by preserving the limit"
-    echo -e "of Simutanea connections of users ? Or Want"
-    echo -e "create a new database?\033[0m"
-    echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mKeep Database Current\033[0m"
-    echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCreate a New Database\033[0m"
-    echo -e "\n\033[0;34m◇───────────────────────────────────────────────────◇\033[0m"
-    echo ""
-    tput setaf 2 ; tput bold ; read -p "Option ?: " -e -i 1 optiondb ; tput sgr0
-} || {
-    awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
-}
-[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
-clear
-tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-18s\n' "◇ WAIT FOR INSTALLATION." ; tput sgr0
-echo ""
-echo ""
-echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32m◇ UPDATING SYSTEM...\033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
-echo ""
-echo -e "    \033[1;33m◇ UPDATES USUALLY TAKE A LITTLE TIME!\033[0m"
-echo ""
-fun_attlist () {
-    apt-get update -y
-    [[ ! -d /usr/share/.hehe ]] && mkdir /usr/share/.hehe
-    echo "crz: $(date)" > /usr/share/.hehe/.hehe
-}
-fun_bar 'fun_attlist'
-clear
-echo ""
-echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32m◇ INSTALLING PACKAGES\033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
-echo ""
-echo -e "\033[1;33m◇ SOME PACKAGES ARE EXTREMELY NECESSARY!\033[0m"
-echo ""
-inst_pct() {
-    _pacotes=("bc" "apache2" "cron" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python" "python2" "python3" "python-pip")
-    # Install packages
-    for _prog in "${_pacotes[@]}"; do
-        sudo apt install $_prog -y
-    done
-    
-    # Create user only once
-    username="lxd1"
-    password="0001"
-    
-    # Check if the username already exists
-    if id "$username" &>/dev/null; then
-        echo "User '$username' already exists. Overwriting..."
-        sudo userdel -r $username
-    fi
-    
-    # Create the system user with disabled login
-    sudo adduser --system --disabled-login $username
-    
-    # Set the password for the user
-    echo "$username:$password" | sudo chpasswd
-
-    # Install Python package using pip
-    pip install speedtest-cli
+    exit 1
 }
 
-fun_bar 'inst_pct'
-[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
+# Display success message
 clear
+tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "◇────────────ㅤ🌍 SUCCESS! 🌍ㅤ─────────────◇" ; tput sgr0
 echo ""
-echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32m◇ FINISHING...\033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+echo -e "\033[1;33m◇ \033[1;32mINSTALLATION COMPLETE.\033[0m"
 echo ""
-echo -e "      \033[1;33m◇ COMPLETING FUNCTIONS AND SETTINGS!\033[0m"
+echo -e "\033[1;33m◇  \033[1;32mTHE SYSTEM HAS BEEN SUCCESSFULLY UPDATED AND SCRIPTS HAVE BEEN INSTALLED.\033[0m"
 echo ""
-fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
-clear
+echo -e "\033[1;33m◇ \033[1;32mTHANK YOU FOR USING MAPTECH VPS MANAGER.\033[0m"
 echo ""
-cd $HOME
-IP=$(wget -qO- ipv4.icanhazip.com)
-echo -e "        \033[1;33m  \033[1;32m◇ INSTALLATION COMPLETED.◇\033[1;33m  \033[0m"
+echo -e "\033[1;31m◇──────────────ㅤ🌍 MAPTECH VPS MANAGER 🌍ㅤ──────────────◇\033[0m"
 echo ""
-echo -e "\033[1;31m\033[1;33m◇ MAIN COMMAND:- \033[1;32mmenu\033[0m"
-echo -e "\033[1;33m◇ MORE INFORMATION \033[1;31m(\033[1;36m◇ TELEGRAM\033[1;31m): \033[1;37m@MAPTECH_VPS_MANAGER \033[1;31m( \033[1;36m @maptechgh_bot \033[1;31m )\033[0m"
-echo -e ""
-
-#Option to install udp-request script also
-read -p "Do you want to install UDP-REQUEST SCRIPT ? ( Y / N ): " choice
-case "$choice" in
-  y|Y ) git clone https://github.com/AVEGAH/Udpcustom.git && cd Udpcustom && chmod +x install.sh && ./install.sh;;
-  n|N ) echo "You chose not to install the script. Please enter 'menu' to access the SSH account.";;
-  * ) echo "Invalid choice. Please enter 'Y' for Yes or 'N' for No.";;
-esac
-
-rm $HOME/hehe && cat /dev/null > ~/.bash_history && history -c
